#!/bin/sh
#
# Check if FreeBSD pkg audit shows issues.
#

if [ -f /usr/local/libexec/nagios/utils.sh ]
then
	. /usr/local/libexec/nagios/utils.sh
elif [ -f /opt/csw/libexec/nagios-plugins/utils.sh ]
then
	. /opt/csw/libexec/nagios-plugins/utils.sh
else
	echo "utils.sh not found"
	exit 3
fi


if [ ! -x /usr/local/sbin/pkg ]
then
	echo "pkg not found"
	exit 3
fi

response=`/usr/local/sbin/pkg audit`

echo "$response" | grep '^0 problem' > /dev/null 2>&1
if [ $? -ne 0 ]
then
	echo "$response"
	exit ${STATE_WARNING}
fi

echo "OK"
exit ${STATE_OK}
