#!/bin/sh
#
# Query external DNS for guengel.ch and compare with external ip
if [ -f /usr/local/libexec/nagios/utils.sh ]
then
	. /usr/local/libexec/nagios/utils.sh
elif [ -f /opt/csw/libexec/nagios-plugins/utils.sh ]
then
	. /opt/csw/libexec/nagios-plugins/utils.sh
else
	echo "utils.sh not found"
	exit 3
fi

expected_ip=`curl -s https://api.ipify.org`
actual_ip=`host -t a guengel.ch 8.8.8.8 | awk '/has address/ { print $4 }'`

msg="Expected IP: $expected_ip, actual IP: $actual_ip"
if [ "$expected_ip" != "$actual_ip" ]
then
    echo "ERROR: ${msg}"
    exit ${STATE_CRITICAL}
fi

echo "OK: ${msg}"
exit ${STATE_OK}
