#!/bin/sh

. /usr/local/libexec/nagios/utils.sh

secure_level=`sysctl kern.securelevel | cut -f 2 -d ' '`

if [ $secure_level -gt 0 ]
then
	echo "Securelevel above 0: $secure_level"
	exit $STATE_CRITICAL
fi

echo "Ok"
exit $STATE_OK
