#!/bin/sh
#

# PROVIDE: keycloak
# REQUIRE: DAEMON

. /etc/rc.subr

name="keycloak"
rcvar=keycloak_enable

user=keycloak
group=keycloak

keycloak_chdir="/usr/local/keycloak"
command="/usr/local/keycloak/bin/kc.sh"
pidfile="/var/run/${name}/pid"
procname="daemon"
start_precmd="${name}_prestart"
start_cmd="/usr/sbin/daemon -u ${user} -P ${pidfile} -p ${pidfile}.child -f ${command} start"

keycloak_prestart() {
    install -d -o ${user} -g ${group} /var/run/${name}
}

load_rc_config $name
run_rc_command "$1"
