#!/bin/sh
#
# Backup to colossus

/usr/local/bin/rsync \
    -a \
    --delete \
    --delete-excluded \
    --exclude .snap \
    --exclude .sujournal \
    --password-file /usr/local/etc/rsync/rsync.secret \
    /data/ ec2-backup-web@colossus.kruemel.home::ec2-backup-web/`hostname`/
