#!/bin/sh
#
# Backup to gizmo

/usr/local/bin/rsync \
    -a \
    --delete \
    --delete-excluded \
    --exclude .snap \
    --exclude .sujournal \
    --password-file /usr/local/etc/rsync/rsync.secret \
    /data/postgres/backups ec2-backup-db@gizmo.kruemel.home::ec2-backup-db/`hostname`/
